version: '3'

services:
  app:
    build: .
    image: dev-environment
    container_name: dev_env
    volumes:
      - /home/j/Desarrollo/:/usr/src/app/workspace
      #- C:\Users\Jesús\OneDrive - UNIR\GitHub Projects\Desarrollo:/usr/src/app
    stdin_open: true  # Para habilitar la entrada interactiva (útil para shells)
    tty: true          # Asignar un terminal (útil para shells)